/* eslint-disable no-console */
// eslint-disable-next-line import/extensions
import Hashmap from './hashmap.mjs';

const hashMap = new Hashmap();

console.log(hashMap.set('Carlos', 'This is an old value'));
console.log(hashMap.set('Bouya', 'This is testing'));
console.log(hashMap.set('Nicolas', 'I am Nicolas'));
console.log(hashMap.set('Stephane', 'I am really in a bucket ?'));
console.log(hashMap.set('Julien', 'Help me !'));
console.log(hashMap.set('Rose', "Yes Nicolas, we know you're Nicolas !"));
console.log(hashMap.set('Bob', '1'));
console.log(hashMap.set('Baby', 'Areuh'));
console.log(hashMap.set('Grandpa', 'Zzzzzzz'));
console.log(hashMap.set('Johnny', 'Ameriiiica !'));
console.log(hashMap.set('Bobby', 'Iam not Bob !'));
console.log(hashMap.set('Billie', 'Hey liche ! '));
console.log(hashMap.set('tona', '1'));
console.log(hashMap.set('tonb', '1'));
console.log(hashMap.set('tonc', '1'));
console.log(hashMap.set('tond', '1'));
console.log(hashMap.set('tone', '1'));
console.log(hashMap.set('tonf', '1'));
console.log(hashMap.set('tong', '1'));
console.log(hashMap.set('tonh', '1'));
console.log(hashMap.set('toni', '1'));
console.log(hashMap.set('tonj', '1'));
console.log(hashMap.set('tonk', '1'));
console.log(hashMap.set('tonl', '1'));
console.log(hashMap.set('tonm', '1'));
console.log(hashMap.set('tonn', '1'));
console.log(hashMap.set('tono', '1'));
console.log(hashMap.set('tonp', '1'));
console.log(hashMap.set('tonq', '1'));
console.log(hashMap.set('tonr', '1'));
console.log(hashMap.set('tons', '1'));
console.log(hashMap.set('a', '1'));
console.log(hashMap.set('b', '1'));
console.log(hashMap.set('c', '1'));
console.log(hashMap.set('d', '1'));
console.log(hashMap.set('e', '1'));
console.log(hashMap.set('f', '1'));
console.log(hashMap.set('g', '1'));
console.log(hashMap.set('h', '1'));
console.log(hashMap.set('i', '1'));
console.log(hashMap.set('j', '1'));
console.log(hashMap.set('k', '1'));
console.log(hashMap.set('l', '1'));
console.log(hashMap.set('m', '1'));
console.log(hashMap.set('n', '1'));
console.log(hashMap.set('o', '1'));
console.log(hashMap.set('p', '1'));
console.log(hashMap.set('q', '1'));
console.log(hashMap.set('r', '1'));
console.log(hashMap.set('s', '1'));
console.log(hashMap.set('t', '1'));
console.log(hashMap.set('u', '1'));
console.log(hashMap.set('v', '1'));
console.log(hashMap.set('w', '1'));
console.log(hashMap.set('x', '1'));
console.log(hashMap.set('y', '1'));
console.log(hashMap.set('z', '1'));
console.log(hashMap.set('aa', '1'));
console.log(hashMap.set('ab', '1'));
console.log(hashMap.set('ac', '1'));
console.log(hashMap.list);
console.log(hashMap.capacity);
console.log(hashMap.loadfactor);
console.log(hashMap.numberOfKeys);
